import { createHmac, timingSafeEqual } from "node:crypto";

import { getPaystackConfig } from "@/lib/paystack/config";
import type { BillingPlan } from "@/lib/monetization/types";

/**
 * Minimal Paystack client over the REST API (no SDK). Dormant unless a secret key
 * is configured — and the config now comes from the ADMIN DASHBOARD (the `settings`
 * table, key `paystack`), falling back to the legacy env vars. See lib/paystack/config.ts.
 *
 * Paystack signs webhooks with HMAC-SHA512 of the raw body using the SECRET key.
 */

const BASE = "https://api.paystack.co";

export async function paystackEnabled(): Promise<boolean> {
  const { secretKey } = await getPaystackConfig();
  return !!secretKey;
}

export async function planCodeForPlan(plan: BillingPlan): Promise<string | null> {
  const { planPro, planBusiness } = await getPaystackConfig();
  if (plan === "pro") return planPro || null;
  if (plan === "business") return planBusiness || null;
  return null;
}

export async function planForPlanCode(code: string | undefined | null): Promise<BillingPlan> {
  const { planPro, planBusiness } = await getPaystackConfig();
  if (code && code === planBusiness) return "business";
  if (code && code === planPro) return "pro";
  return "free";
}

async function paystack<T = Record<string, unknown>>(
  path: string,
  init: { method?: string; body?: unknown } = {},
): Promise<T> {
  const { secretKey } = await getPaystackConfig();
  if (!secretKey) throw new Error("Paystack is not configured");
  const res = await fetch(`${BASE}${path}`, {
    method: init.method ?? "GET",
    headers: {
      Authorization: `Bearer ${secretKey}`,
      "Content-Type": "application/json",
    },
    body: init.body ? JSON.stringify(init.body) : undefined,
    signal: AbortSignal.timeout(15_000),
  });
  const json = (await res.json()) as T & { status?: boolean; message?: string };
  if (!res.ok || json.status === false) {
    throw new Error(json.message || `Paystack ${path} failed`);
  }
  return json;
}

/** The plan's amount (in kobo). Paystack's initialize requires an amount even
 * when a plan is passed, so we read it from the plan to stay correct. */
async function planAmount(planCode: string): Promise<number | undefined> {
  try {
    const p = await paystack<{ data: { amount: number } }>(`/plan/${planCode}`);
    return p.data?.amount;
  } catch {
    return undefined;
  }
}

/**
 * Starts a subscription checkout: initialize a transaction tied to a plan and
 * return Paystack's hosted authorization URL to redirect the user to.
 */
export async function initializeTransaction(opts: {
  email: string;
  planCode: string;
  userId: string;
  callbackUrl: string;
}): Promise<string> {
  const amount = await planAmount(opts.planCode);
  const data = await paystack<{ data: { authorization_url: string } }>(
    "/transaction/initialize",
    {
      method: "POST",
      body: {
        email: opts.email,
        plan: opts.planCode,
        // Required by the API; the plan amount governs the actual charge.
        ...(amount != null ? { amount } : {}),
        callback_url: opts.callbackUrl,
        metadata: { user_id: opts.userId },
      },
    },
  );
  return data.data.authorization_url;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  A ONE-OFF AI BALANCE TOP-UP
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Owner, 2026-09-09, standing rule §13: "Use the existing integrated Paystack
 * payment infrastructure. Do NOT create a second payment provider."
 *
 * ── 🔴 A CHARGE, NOT A SUBSCRIPTION ─────────────────────────────────────────
 *
 * `initializeTransaction` above takes a PLAN and creates a recurring
 * subscription. A balance top-up is the opposite: one payment, no plan, no
 * renewal. Passing a plan code would enrol somebody in a monthly charge for
 * what they thought was a single purchase — so this deliberately does not
 * accept one, rather than defaulting it to null and hoping.
 *
 * ── 🔴 THE CURRENCY IS EXPLICIT, AND THAT IS THE POINT ──────────────────────
 *
 * Paystack amounts are in the SUBUNIT of the account's currency and the API
 * does not report which one it assumed. `500` on an NGN account is ₦5.00; on a
 * USD account it is $5.00 — different by roughly a factor of 1,500, with
 * nothing in the response to distinguish them. Stating it means a mismatch is
 * refused at checkout instead of silently mispricing every sale.
 *
 * ── The reference is OURS, and it is the idempotency key ────────────────────
 *
 * Paystack echoes it back on the webhook, and `credit_ai_balance` has a unique
 * index on it — so a delivery repeated three times credits once. Generated by
 * the caller rather than here, because the caller is the one that must be able
 * to recognise it later.
 */
export async function initializeAiTopup(opts: {
  email: string;
  userId: string;
  /** Minor units — cents, kobo, pesewas. Never a decimal. */
  amount: number;
  currency: string;
  reference: string;
  callbackUrl: string;
}): Promise<string> {
  const data = await paystack<{ data: { authorization_url: string } }>(
    "/transaction/initialize",
    {
      method: "POST",
      body: {
        email: opts.email,
        amount: opts.amount,
        currency: opts.currency,
        reference: opts.reference,
        callback_url: opts.callbackUrl,
        /*
          🔴 `purpose` is what the webhook branches on. Without it an AI top-up
          is indistinguishable from a subscription charge, and `syncPaystackEvent`
          would try to resolve it to a plan — finding none, and quietly doing
          nothing with somebody's money.
        */
        metadata: {
          user_id: opts.userId,
          purpose: AI_TOPUP_PURPOSE,
          ai_topup_cents: opts.amount,
        },
      },
    },
  );
  return data.data.authorization_url;
}

/**
 * The marker that says a `charge.success` is a Frenz AI top-up.
 *
 * A constant rather than a string literal in two files, because the webhook and
 * the initializer have to agree exactly and they are never read together.
 */
export const AI_TOPUP_PURPOSE = "frenz_ai_topup";

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  ASK PAYSTACK WHAT ACTUALLY HAPPENED TO A TRANSACTION
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Owner, 2026-09-09: "i just recharged but it didnt show in the dashboard."
 *
 * ── 🔴 WHY A WEBHOOK ALONE WAS NOT ENOUGH ───────────────────────────────────
 *
 * The webhook is the authority and stays the authority — but it is delivered to
 * us out of band, and there are three ordinary ways a member can be looking at
 * a stale balance thirty seconds after paying:
 *
 *   · the redirect back from Paystack RACES the delivery, and usually wins;
 *   · the webhook URL is not configured on the Paystack dashboard at all, which
 *     is a settings screen we do not control and cannot detect from here;
 *   · a delivery failed and is waiting on Paystack's retry schedule.
 *
 * In all three the money moved and the member sees nothing. This is the read
 * that resolves it: the browser tells us a REFERENCE, and we ask Paystack — on
 * our own server, with our own secret key — what became of it.
 *
 * ── 🔴 THE BROWSER SUPPLIES AN IDENTIFIER, NEVER AN OUTCOME ─────────────────
 *
 * §13: "Payment confirmation must be verified server-side. Do not credit the
 * balance based solely on a frontend success callback." That rule is about
 * TRUSTING the callback, and nothing here does: the status, the amount and the
 * currency in the returned object are Paystack's own, fetched over TLS with the
 * secret key. A forged reference verifies as somebody else's transaction or as
 * nothing at all, and the caller checks the metadata before crediting anybody.
 */
export interface PaystackVerifiedCharge {
  /** "success", "failed", "abandoned"… Paystack's own word for it. */
  status?: string;
  /** Minor units, in `currency`. What SETTLED, not what we asked for. */
  amount?: number;
  currency?: string;
  reference?: string;
  metadata?: { user_id?: string; purpose?: string };
}

export async function verifyTransaction(reference: string): Promise<PaystackVerifiedCharge> {
  const data = await paystack<{ data: PaystackVerifiedCharge }>(
    `/transaction/verify/${encodeURIComponent(reference)}`,
  );
  return data.data ?? {};
}

/** Hosted link for a member to update card / cancel their subscription. */
export async function subscriptionManageLink(subscriptionCode: string): Promise<string> {
  const data = await paystack<{ data: { link: string } }>(
    `/subscription/${subscriptionCode}/manage/link`,
  );
  return data.data.link;
}

export async function verifyPaystackSignature(payload: string, header: string | null): Promise<boolean> {
  const { secretKey } = await getPaystackConfig();
  if (!secretKey || !header) return false;
  const hash = createHmac("sha512", secretKey).update(payload).digest("hex");
  try {
    return timingSafeEqual(Buffer.from(hash), Buffer.from(header));
  } catch {
    return false;
  }
}

/** Shapes of the webhook payloads we care about. */
export interface PaystackEventData {
  customer?: { email?: string; customer_code?: string };
  plan?: { plan_code?: string };
  subscription_code?: string;
  email_token?: string;
  next_payment_date?: string;
  status?: string;
  /**
   * 🔴 What this payment was FOR. A Frenz AI top-up and a subscription charge
   * both arrive as `charge.success`, and this is the only thing that tells them
   * apart — see the branch in the webhook route.
   */
  metadata?: { user_id?: string; purpose?: string; ai_topup_cents?: number | string };
  /**
   * Minor units, as PAYSTACK reports them.
   *
   * ⚠️ Trusted over our own metadata when crediting, and that ordering is
   * deliberate: this is what was actually settled. `ai_topup_cents` is what we
   * asked for, and if the two ever disagree the money that moved is the truth.
   */
  amount?: number;
  currency?: string;
  /** Our own reference, echoed back. The idempotency key for the credit. */
  reference?: string;
}
