"use client";

import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, Check, KeyRound, Loader2, Mail, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { type FormEvent, useEffect, useRef, useState } from "react";

import { FLoaderOverlay } from "@/features/app-shell/f-loader";
import { OtpInput } from "@/features/auth/otp-input";
import { needsMfaStepUp } from "@/lib/auth/mfa";
import { createClient } from "@/lib/supabase/client";
import { cn } from "@/lib/utils";

type View = "choices" | "email" | "code";

const RESEND_SECONDS = 30;

// "Did you mean …?" for the classic email typos.
const DOMAIN_FIXES: Record<string, string> = {
  "gmail.con": "gmail.com",
  "gmail.co": "gmail.com",
  "gmai.com": "gmail.com",
  "gmial.com": "gmail.com",
  "gamil.com": "gmail.com",
  "googlemail.con": "googlemail.com",
  "hotnail.com": "hotmail.com",
  "hotmial.com": "hotmail.com",
  "hotmail.con": "hotmail.com",
  "yaho.com": "yahoo.com",
  "yahooo.com": "yahoo.com",
  "yahoo.con": "yahoo.com",
  "outlok.com": "outlook.com",
  "outlook.con": "outlook.com",
  "iclould.com": "icloud.com",
  "icloud.con": "icloud.com",
};

function suggestEmail(email: string): string | null {
  const at = email.lastIndexOf("@");
  if (at < 1) return null;
  const domain = email.slice(at + 1).toLowerCase();
  const fix = DOMAIN_FIXES[domain];
  return fix ? `${email.slice(0, at)}@${fix}` : null;
}

/**
 * Passwordless auth (the premium OTP flow): email → 6-digit code → in. The
 * code is generated by Supabase Auth and delivered through a branded Resend
 * email (`/api/auth/otp`); verification is standard `verifyOtp`, so sessions,
 * refresh and multi-device behavior are untouched. Sign-up and sign-in are the
 * same flow — unknown emails are provisioned on first code. Google OAuth stays
 * for existing Google accounts. No passwords anywhere.
 */
export function AuthPanel({ next = "/home" }: { next?: string }) {
  const [view, setView] = useState<View>("choices");
  const [email, setEmail] = useState("");
  const [suggestion, setSuggestion] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [verifying, setVerifying] = useState(false);
  const [verified, setVerified] = useState(false);
  // Set the instant a sign-in commits to leaving this page. Shows the shared F
  // loader (FLoaderOverlay) so the SAME branded mark stays up from the tap
  // through the full-document navigation into the destination's BootSplash — one
  // loader per login, not the old "verifying → you're in" beat plus a separate
  // splash (owner, 2026-07-21).
  const [navigating, setNavigating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [shakeKey, setShakeKey] = useState(0);
  const [countdown, setCountdown] = useState(0);
  // Supabase projects can issue 6–10 digit codes — the server tells us the
  // real length so the boxes always match the email.
  const [codeLength, setCodeLength] = useState(6);
  // Optional password path: sign in with a saved password, or reset it —
  // "Forgot password?" proves ownership with a code, then lands on Account →
  // Password to set the new one.
  const [usePw, setUsePw] = useState(false);
  const [pw, setPw] = useState("");
  const [resetting, setResetting] = useState(false);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const callbackUrl = () => `${window.location.origin}/auth/callback?next=${encodeURIComponent(next)}`;

  /**
   * Leave the login page for `url`, showing the single F loader on the way out.
   * `markSignedIn` sets the `frenz_just_signed_in` cookie that BootSplash reads
   * on the next document to FORCE-show its F splash — so the loader is seamless
   * and deterministic across the navigation (the password/email-code paths never
   * hit /auth/callback, which is the only other place this cookie is set). Only
   * true when landing IN the app; a hop to the MFA challenge is still an auth
   * step, so it navigates under the loader without claiming "signed in" yet.
   */
  const go = (url: string, markSignedIn = false) => {
    if (markSignedIn) {
      try {
        document.cookie = "frenz_just_signed_in=1; path=/";
      } catch {
        /* cookies blocked — the loader still shows, just not force-guaranteed on /home */
      }
    }
    setNavigating(true);
    window.location.assign(url);
  };

  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, []);

  const startCountdown = () => {
    setCountdown(RESEND_SECONDS);
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      setCountdown((s) => {
        if (s <= 1 && timerRef.current) clearInterval(timerRef.current);
        return Math.max(0, s - 1);
      });
    }, 1000);
  };

  const google = async () => {
    setBusy(true);
    setNavigating(true);
    setError(null);
    try {
      const supabase = createClient();
      // signInWithOAuth performs the redirect to Google itself; the F loader
      // covers that moment, then Google's page takes over. The return trip lands
      // on /auth/callback, which sets frenz_just_signed_in for the /home splash.
      const { error } = await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: callbackUrl() } });
      if (error) throw error;
    } catch {
      setError("Google sign-in isn't available right now — use your email instead.");
      setBusy(false);
      setNavigating(false);
    }
  };

  const sendCode = async (target: string) => {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch("/api/auth/otp", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: target }),
      });
      const d = (await res.json().catch(() => ({}))) as { error?: string; codeLength?: number };
      if (!res.ok) {
        setError(d.error || "Couldn't send the code. Try again.");
        return false;
      }
      if (d.codeLength && d.codeLength >= 4 && d.codeLength <= 10) setCodeLength(d.codeLength);
      return true;
    } catch {
      setError("You appear to be offline — check your connection and try again.");
      return false;
    } finally {
      setBusy(false);
    }
  };

  const submitEmail = async (e: FormEvent) => {
    e.preventDefault();
    const target = email.trim().toLowerCase();
    if (!target) return;
    setSuggestion(null);
    if (usePw) {
      // Password path — for accounts that saved one in Account → Password.
      setBusy(true);
      setError(null);
      try {
        const supabase = createClient();
        const { error } = await supabase.auth.signInWithPassword({ email: target, password: pw });
        if (error) {
          setError("Incorrect email or password — or use a sign-in code instead.");
          return;
        }
        if (await needsMfaStepUp(supabase)) {
          go(`/login/mfa-challenge?next=${encodeURIComponent(next)}`);
          return;
        }
        go(next, true);
      } catch {
        setError("Sign-in is unavailable right now — try a code instead.");
      } finally {
        setBusy(false);
      }
      return;
    }
    if (await sendCode(target)) {
      setEmail(target);
      setView("code");
      startCountdown();
    }
  };

  // Forgot password: prove ownership with a code, then choose a new password.
  const forgotPassword = async () => {
    const target = email.trim().toLowerCase();
    if (!target) {
      setError("Enter your email first.");
      return;
    }
    if (await sendCode(target)) {
      setEmail(target);
      setResetting(true);
      setView("code");
      startCountdown();
    }
  };

  const verify = async (code: string) => {
    if (verifying || verified) return;
    setVerifying(true);
    setError(null);
    try {
      const supabase = createClient();
      const { error } = await supabase.auth.verifyOtp({ email, token: code, type: "email" });
      if (error) {
        setError("That code isn't right — check the email and try again.");
        setShakeKey((k) => k + 1);
        return;
      }
      setVerified(true);
      // Hand straight to the single F loader the moment the code is accepted —
      // no separate green-check "you're in" beat before the splash. If the
      // step-up check below throws, the catch clears it and surfaces the error.
      setNavigating(true);
      // A reset lands on Account → Password (verified session) to set the new
      // one; a normal sign-in goes straight in. Either way, an account with a
      // verified 2FA factor clears the step-up challenge first.
      const dest = resetting ? "/account?setPassword=1#password" : next;
      if (await needsMfaStepUp(supabase)) {
        go(`/login/mfa-challenge?next=${encodeURIComponent(dest)}`);
        return;
      }
      go(dest, true);
    } catch {
      setNavigating(false);
      setError("Verification failed — check your connection and try again.");
      setShakeKey((k) => k + 1);
    } finally {
      setVerifying(false);
    }
  };

  const resend = async () => {
    if (countdown > 0 || busy) return;
    if (await sendCode(email)) startCountdown();
  };

  return (
    <>
      {/* The single login loader — same F mark as the cold-start splash. Shown
          the instant a sign-in commits to navigating, and carried across the
          full-document redirect into the destination's own BootSplash. */}
      {navigating ? <FLoaderOverlay /> : null}
      <AnimatePresence mode="wait" initial={false}>
      {view === "choices" ? (
        <motion.div
          key="choices"
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.25 }}
          className="space-y-3"
        >
          <button
            type="button"
            onClick={() => {
              setError(null);
              setView("email");
            }}
            className="group relative inline-flex h-14 w-full items-center justify-center gap-2.5 overflow-hidden rounded-full bg-gradient-to-r from-violet-600 to-fuchsia-600 text-[15px] font-bold text-white shadow-lg shadow-violet-600/30 transition hover:shadow-xl hover:shadow-violet-600/45 active:scale-[0.99]"
          >
            <span className="pointer-events-none absolute inset-0 -translate-x-full bg-gradient-to-r from-transparent via-white/25 to-transparent transition-transform duration-700 group-hover:translate-x-full" />
            <Mail className="h-[18px] w-[18px]" /> Continue with Email
          </button>

          <button
            type="button"
            onClick={google}
            disabled={busy}
            className="inline-flex h-14 w-full items-center justify-center gap-3 rounded-full border border-border/70 bg-background text-[15px] font-semibold text-foreground shadow-sm transition hover:bg-secondary/60 active:scale-[0.99] disabled:opacity-60"
          >
            <GoogleG /> Continue with Google
          </button>

          <button
            type="button"
            onClick={() => {
              setError(null);
              setView("email");
            }}
            className="inline-flex h-14 w-full items-center justify-center rounded-full bg-secondary/70 text-[15px] font-semibold text-foreground transition hover:bg-secondary active:scale-[0.99]"
          >
            I already have an account
          </button>

          {error ? <p className="pt-1 text-center text-sm text-red-400">{error}</p> : null}

          <p className="px-2 pt-1 text-center text-[13px] leading-relaxed text-muted-foreground">
            By continuing, you agree to Frenzsave&apos;s{" "}
            <Link href="/terms" className="font-medium text-violet-500 underline underline-offset-2">Terms of Service</Link>{" "}
            and acknowledge that you&apos;ve read our{" "}
            <Link href="/privacy" className="font-medium text-violet-500 underline underline-offset-2">Privacy Policy</Link>.
          </p>
        </motion.div>
      ) : view === "email" ? (
        <motion.div
          key="email"
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.25 }}
        >
          <button
            type="button"
            onClick={() => {
              setView("choices");
              setError(null);
              setSuggestion(null);
            }}
            className="mb-3 inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground transition hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" /> Back
          </button>

          <h2 className="text-lg font-extrabold tracking-tight">{usePw ? "Welcome back" : "What's your email?"}</h2>
          <p className="mb-4 mt-0.5 text-sm text-muted-foreground">
            {usePw
              ? "Sign in with the password you saved."
              : "We'll email you a secure sign-in code — no password to remember. New here? The same code creates your account."}
          </p>

          <form onSubmit={submitEmail} className="space-y-3">
            <Field icon={<Mail className="h-[18px] w-[18px]" />}>
              <input
                type="email"
                required
                autoFocus
                value={email}
                onChange={(e) => {
                  setEmail(e.target.value);
                  setSuggestion(suggestEmail(e.target.value.trim()));
                }}
                placeholder="you@email.com"
                aria-label="Email"
                autoComplete="email"
                className={INPUT}
              />
            </Field>

            {suggestion ? (
              <button
                type="button"
                onClick={() => {
                  setEmail(suggestion);
                  setSuggestion(null);
                }}
                className="w-full rounded-xl bg-secondary/60 px-3 py-2 text-left text-sm text-muted-foreground transition hover:bg-secondary hover:text-foreground"
              >
                Did you mean <span className="font-semibold text-foreground">{suggestion}</span>?
              </button>
            ) : null}

            {usePw ? (
              <Field icon={<KeyRound className="h-[18px] w-[18px]" />}>
                <input
                  type="password"
                  required
                  value={pw}
                  onChange={(e) => setPw(e.target.value)}
                  placeholder="Password"
                  aria-label="Password"
                  autoComplete="current-password"
                  className={INPUT}
                />
              </Field>
            ) : null}

            <button
              type="submit"
              disabled={busy || !email.trim() || (usePw && !pw)}
              className="group relative inline-flex h-[52px] w-full items-center justify-center gap-2 overflow-hidden rounded-2xl bg-gradient-to-r from-violet-600 to-fuchsia-600 text-[15px] font-bold text-white shadow-lg shadow-violet-600/25 transition hover:shadow-xl active:scale-[0.99] disabled:opacity-60"
            >
              <span className="pointer-events-none absolute inset-0 -translate-x-full bg-gradient-to-r from-transparent via-white/20 to-transparent transition-transform duration-700 group-hover:translate-x-full" />
              {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
              {usePw ? "Sign in" : "Continue"}
            </button>
          </form>

          <div className="mt-3 flex items-center justify-center gap-4 text-xs font-medium">
            <button
              type="button"
              onClick={() => {
                setUsePw((v) => !v);
                setError(null);
              }}
              className="text-muted-foreground transition hover:text-foreground"
            >
              {usePw ? "Use a sign-in code instead" : "Sign in with a password"}
            </button>
            {usePw ? (
              <button type="button" onClick={forgotPassword} disabled={busy} className="text-violet-500 hover:underline disabled:opacity-60">
                Forgot password?
              </button>
            ) : null}
          </div>

          {error ? <p className="mt-3 text-center text-sm text-red-400">{error}</p> : null}
        </motion.div>
      ) : (
        <motion.div
          key="code"
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.25 }}
        >
          <button
            type="button"
            onClick={() => {
              setView("email");
              setResetting(false);
              setError(null);
            }}
            className="mb-3 inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground transition hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" /> Change email
          </button>

          <h2 className="text-lg font-extrabold tracking-tight">{resetting ? "Reset your password" : "Verification code"}</h2>
          <p className="mb-5 mt-0.5 text-sm text-muted-foreground">
            We&apos;ve sent a secure verification code to <span className="font-semibold text-foreground">{email}</span>.
            {resetting ? " Verify it and you'll choose a new password right after." : ""}
          </p>

          <OtpInput length={codeLength} onComplete={verify} disabled={verifying || verified} shake={shakeKey} />

          <div className="mt-4 flex min-h-6 items-center justify-center gap-1.5 text-sm" aria-live="polite">
            {verified ? (
              <span className="inline-flex items-center gap-1.5 font-semibold text-emerald-500">
                <Check className="h-4 w-4" /> You&apos;re in — taking you home
              </span>
            ) : verifying ? (
              <span className="inline-flex items-center gap-1.5 text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" /> Verifying
              </span>
            ) : error ? (
              <span className="text-red-400">{error}</span>
            ) : (
              <span className="inline-flex items-center gap-1.5 text-muted-foreground">
                <ShieldCheck className="h-4 w-4" /> The code verifies automatically
              </span>
            )}
          </div>

          <button
            type="button"
            onClick={resend}
            disabled={countdown > 0 || busy}
            className={cn(
              "mt-3 w-full text-center text-sm font-medium transition",
              countdown > 0 ? "text-muted-foreground/60" : "text-violet-500 hover:underline",
            )}
          >
            {countdown > 0 ? `Resend code in ${countdown}s` : busy ? "Sending…" : "Resend code"}
          </button>
        </motion.div>
      )}
      </AnimatePresence>
    </>
  );
}

const INPUT = "h-[52px] w-full rounded-2xl bg-transparent pl-11 pr-4 text-[15px] outline-none placeholder:text-muted-foreground/60";

function Field({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="group relative rounded-2xl bg-secondary/40 ring-1 ring-inset ring-border/60 transition focus-within:bg-background focus-within:shadow-[0_0_0_4px_rgba(139,92,246,0.12)] focus-within:ring-2 focus-within:ring-violet-500/55">
      <span className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground transition group-focus-within:text-violet-500">{icon}</span>
      {children}
    </div>
  );
}

function GoogleG() {
  return (
    <svg viewBox="0 0 24 24" className="h-5 w-5 shrink-0" aria-hidden="true">
      <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 0 1-2.2 3.32v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.1Z" />
      <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84A11 11 0 0 0 12 23Z" />
      <path fill="#FBBC05" d="M5.84 14.1a6.6 6.6 0 0 1 0-4.2V7.06H2.18a11 11 0 0 0 0 9.88l3.66-2.84Z" />
      <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.06l3.66 2.84C6.71 7.31 9.14 5.38 12 5.38Z" />
    </svg>
  );
}
